#!/bin/bash
##me@danielpeluso.com
###ip to int converter

echo "Please type the ip address you wish to convert, followed by [Enter]:"

read ip #take in ip argument

ip2conv(){
   	   declare -i a b c d; #delcaring abcd as integers
   	   IFS=. read a b c d <<<"$ip"; #seperating to individual fields
   	   echo "$(((a<<24)+(b<<16)+(c<<8)+d))"; #calculating each octet
	}	

a=$(ip2conv "$ip")
echo "$ip converts to Int=$a"
